### ISSUE TITLE
Unable to install the project.

### ISSUE THREAD

**Issue by carlosfranzreb** [sorinMD/StacSettlers#1]
Hello,

I am trying to install the project and failing to do so. First, I was missing the DeepCatan JAR after cloning the project. I tried creating that JAR in the respective project and dragging it to this one. But it didn't work.

When running `mvn clean install`, I become the following errors:
```
[ERROR] /C:/docs/cs/thesis/catan/code/StacSettlers/src/mcts/seeder/nn/SampleNNCatanSeeder.java:[6,40] package org.deeplearning4j.nn.multilayer does not exist
[ERROR] /C:/docs/cs/thesis/catan/code/StacSettlers/src/mcts/seeder/nn/SampleNNCatanSeeder.java:[7,35] package org.nd4j.linalg.api.ndarray does not exist
[ERROR] /C:/docs/cs/thesis/catan/code/StacSettlers/src/mcts/seeder/nn/SampleNNCatanSeeder.java:[8,31] package org.nd4j.linalg.dataset does not exist
[ERROR] /C:/docs/cs/thesis/catan/code/StacSettlers/src/mcts/seeder/nn/SampleNNCatanSeeder.java:[9,31] package org.nd4j.linalg.factory does not exist
[ERROR] /C:/docs/cs/thesis/catan/code/StacSettlers/src/mcts/seeder/nn/SampleNNCatanSeeder.java:[13,12] package data does not exist
```

It seems that the DeepCatan JAR I'm using is not working.

Could you help me out?

Kind regards,
Carlos

**Comment by jdmonin** [comment]
Hello Carlos,

The setup for StacSettlers is definitely unintuitive.

Also, there's a more up-to-date fork maintained at https://github.com/ruflab/StacSettlers . You will probably want to use that one instead. It has some quality-of-life improvements, fairly responsive maintainers, and some time this year will get a large upgrade to use the latest JSettlers v2 code from https://github.com/jdmonin/JSettlers2 .

I was able to build StacSettlers on ubuntu 20.04 with these commands, and a few caveats I'll go into afterwards:

```
sudo apt update
sudo apt install openjdk-8-jdk make git git-lfs
sudo apt install maven=3.6.3-1

git clone https://github.com/ruflab/StacSettlers
cd StacSettlers
git lfs install && git-lfs fetch && git-lfs checkout   # this failed (quota), see below
# (manually obtain or build DeepCatan-0.0.1.jar and place into ./lib directory)
make build   # outputs harmless warnings about /usr/libexec/java_home not found
```

That build produced the expected JARs:

```
[INFO] Scanning for projects...
[WARNING] The project STAC:STACSettlers:jar:1.0 uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-compiler-plugin/3.5.1/maven-compiler-plugin-3.5.1.pom
...
[WARNING] maven-shade-plugin has detected that some class files are
[WARNING] present in two or more JARs. When this happens, only one
[WARNING] single version of the class is copied to the uber jar.
[WARNING] Usually this is not harmful and you can skip these warnings,
[WARNING] otherwise try to manually exclude artifacts based on
[WARNING] mvn dependency:tree -Ddetail=true and the above output.
[WARNING] See http://maven.apache.org/plugins/maven-shade-plugin/
[INFO] Attaching shaded artifact.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:07 min
[INFO] Finished at: 2021-01-31T18:33:03Z
[INFO] ------------------------------------------------------------------------

$ ls -l target/
total 182812
drwxrwxr-x  7 jtest jtest      4096 Jan 31 18:32 ./
drwxrwxr-x 12 jtest jtest      4096 Jan 31 18:32 ../
-rw-rw-r--  1 jtest jtest 179317365 Jan 31 18:33 STACSettlers-1.0-bin.jar
-rw-rw-r--  1 jtest jtest   7841581 Jan 31 18:32 STACSettlers-1.0.jar
drwxrwxr-x 10 jtest jtest      4096 Jan 31 18:32 classes/
-rw-rw-r--  1 jtest jtest       643 Jan 31 18:32 config.txt
drwxrwxr-x  3 jtest jtest      4096 Jan 31 18:32 generated-sources/
drwxrwxr-x  2 jtest jtest      4096 Jan 31 18:32 maven-archiver/
drwxrwxr-x  3 jtest jtest      4096 Jan 31 18:32 maven-status/
drwxrwxr-x  2 jtest jtest      4096 Jan 31 18:32 test-classes/

```

I can run it as:

```
java -cp target/STACSettlers-1.0-bin.jar soc.server.SOCServer -Djsettlers.startrobots=8 8880 16 dbUser dbPass &

java -cp target/STACSettlers-1.0-bin.jar soc.client.SOCPlayerClient localhost 8880
```

Here are the caveats:
- git-lfs gave a 'data quota' error from github, but I worked around that by using a copy of DeepCatan-0.0.1.jar I already had. Allegedly the monthly quota will refill itself tomorrow Feb 1st.
- The Makefile sets the JAVA_HOME env variable from `/usr/libexec/java_home` to be compatible with Mac OS, and that fails on other OSes but is okay because java can auto-configure its JAVA_HOME value
- Until you go through database setup, the server refuses to auth clients: You are able to run Practice games but not server games

Hopefully that's helpful info.

Sincerely,
Jeremy Monin
jsettlers developer and StacSettlers contributor

**Comment by sorinMD** [comment]
Hi Carlos,

It seems the issue you are facing is due to git lfs being disabled as my git lfs quota has been exceeded. You should be able to pull it now as it should have reset for this month. To install, you need to manually install the 5 jars which were not available on Maven Central at the time of release (note that there is a script to help with this installation).

Unfortunately, I am no longer actively participating in the STAC project and I cannot provide long-term support due to time constraints. If you choose to clone any of the forks, do note that you may run into the same problem since the git lfs quota counts against the root owner, i.e. the owner of this repo. Please contact the current [STAC](https://www.irit.fr/STAC/index.html) developers (or Jeremy Monin above?) and they should be able to provide support and the files you need.

All the best,
Mihai

**Comment by carlosfranzreb** [comment]
Thank you, Jeremy, for the thorough response. I had to add the deepCatan dependencies to the POM file of StacSettlers, and now it works. I'm also on the fork you mentioned; thanks for the tip.

Kind regards,
Carlos

**Comment by jdmonin** [comment]
Hello Carlos,

You're welcome, that's good to hear. Have fun!

Thanks also Mihai for all your past work on StacSettlers and publishing on GitHub.

Sincerely,
Jeremy

**Comment by carlosfranzreb** [comment]
Yes, thank you Mihai!
